name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - "release-*"

env:
  GO_VERSION: "1.22.x"
  WORKDIR: src/github.com/containers/otelttrpc

permissions:
  contents: read
  pull-requests: read

jobs:
  #
  # Project checks
  #
  project:
    name: Project Checks
    runs-on: ubuntu-22.04
    timeout-minutes: 5

    steps:
      - uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
        with:
          go-version: ${{ env.GO_VERSION }}

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          path: ${{ env.WORKDIR }}
          fetch-depth: 25

      - uses: containerd/project-checks@d7751f3c375b8fe4a84c02a068184ee4c1f59bc4 # v1.2.2
        with:
          working-directory: ${{ env.WORKDIR }}

  #
  # Linters
  #
  linters:
    name: Linters
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10

    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          path: ${{ env.WORKDIR }}

      - name: Setup golang toolchain
        uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9 # v8.0.0
        with:
          version: v1.60.3
          args: --timeout=10m
          skip-cache: true
          working-directory: ${{ env.WORKDIR }}

  #
  # Tests and other checks
  #
  tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]

    name: Tests and other checks
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          path: ${{ env.WORKDIR }}

      - name: Setup golang toolchain
        uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Verify go modules
        working-directory: ${{ env.WORKDIR }}
        run: |
          make verify-vendor

      - name: Run tests
        working-directory: ${{ env.WORKDIR }}
        run: |
          make test

      - name: Test build examples
        working-directory: ${{ env.WORKDIR }}
        run: |
          cd example
          make

      - name: Coverage
        working-directory: ${{ env.WORKDIR }}
        run: |
          make coverage TESTFLAGS_RACE=-race